version: '3.0'
services:

  proxy:
    restart: always
    ports:
      - 81:81
    build:
      context: .
      dockerfile: nginx/Dockerfile
    links:
      - webapp
    depends_on:
      - webapp

  webapp:
    restart: always
    build:
      context: .
      dockerfile: web_app/Dockerfile
    ports:
      - 8080

